"""added defaults

Revision ID: 1687135f367e
Revises: 0694f1dd111a
Create Date: 2022-11-12 15:35:12.442820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1687135f367e'
down_revision = '0694f1dd111a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
