"""Added relationship column

Revision ID: 22f43e3ce704
Revises: ff11768a9708
Create Date: 2022-11-12 13:18:09.347039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f43e3ce704'
down_revision = 'ff11768a9708'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
