"""setted defaults

Revision ID: 245d7f32a0ed
Revises: 31340fcac8ac
Create Date: 2022-11-12 11:30:53.379229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245d7f32a0ed'
down_revision = '31340fcac8ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
