"""added games

Revision ID: 25df9c325a58
Revises: 9b58efb995a9
Create Date: 2022-11-12 11:11:09.959072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25df9c325a58'
down_revision = '9b58efb995a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
