"""Added status rel

Revision ID: 6d64b1471abb
Revises: 22f43e3ce704
Create Date: 2022-11-12 13:26:43.783990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d64b1471abb'
down_revision = '22f43e3ce704'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
