"""added player

Revision ID: 70179885edf4
Revises: 79055ecd2ebc
Create Date: 2022-11-12 11:20:17.515745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70179885edf4'
down_revision = '79055ecd2ebc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    # ### end Alembic commands ###
