"""second

Revision ID: a595a1e029f6
Revises: fc7061ecea08
Create Date: 2022-11-12 11:08:07.806928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a595a1e029f6'
down_revision = 'fc7061ecea08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###
