"""added games second

Revision ID: c04329d2f2b4
Revises: 25df9c325a58
Create Date: 2022-11-12 11:12:12.619010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04329d2f2b4'
down_revision = '25df9c325a58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
