"""edited player

Revision ID: e7e99a3a290a
Revises: b7d2a6b98a69
Create Date: 2022-11-12 11:22:31.948457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e99a3a290a'
down_revision = 'b7d2a6b98a69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_status', sa.Column('winner_player_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'game_status', type_='foreignkey')
    op.create_foreign_key(None, 'game_status', 'player', ['winner_player_id'], ['id'])
    op.drop_column('game_status', 'player_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_status', sa.Column('player_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'game_status', type_='foreignkey')
    op.create_foreign_key(None, 'game_status', 'player', ['player_id'], ['id'])
    op.drop_column('game_status', 'winner_player_id')
    # ### end Alembic commands ###
