"""added relationship

Revision ID: ff11768a9708
Revises: 245d7f32a0ed
Create Date: 2022-11-12 13:01:20.569813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff11768a9708'
down_revision = '245d7f32a0ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
